### ISSUE TITLE
Labeling symbol name in plot_gene_trajectory_3d

### ISSUE THREAD

**Issue by yc508** [KlugerLab/GeneTrajectory-python#7]
Hi,

Thank you very much for developing this amazing tools. I am new to python and I have a quick question. If there is a way to label symbol  name in the figure generated in plot_gene_trajectory_3d? And if there is a way to extract the genes information from each trajectory? Thank you very much!

**Comment by fra-pcmgf** [comment]
Hi, 
Thanks for your message, I'm happy to see you are using the tool! 

The `gene_trajectory` is a pandas DataFrame with all the information about the trajectory. 
For example, using the data in [the tutorial](https://genetrajectory-python.readthedocs.io/latest/notebooks/tutorial_human_myeloid.html), you can see the information for Trajectory-1 using the 'Pseudoorder-1' column as
```
gene_trajectory[gene_trajectory['Pseudoorder-1'] > 0].sort_values('Pseudoorder-1', ascending=False)
```
which will show a table like
```
	DM_1	DM_2	DM_3	DM_4	DM_5	selected	Pseudoorder-1	Pseudoorder-2	Pseudoorder-3
DEPTOR	-0.001002	0.093192	-0.094116	-0.022790	0.066779	Trajectory-1	40.0	0.0	0.0
PPP1R14A	-0.001123	0.095193	-0.097428	-0.023587	0.071194	Trajectory-1	39.0	0.0	0.0
PKIB	-0.001051	0.087549	-0.086126	-0.020310	0.056938	Trajectory-1	38.0	0.0	0.0
GRIP1	-0.001182	0.092300	-0.093527	-0.022337	0.066703	Trajectory-1	37.0	0.0	0.0
```

or you can extract the gene list (here for Trajectory 1) similarly as 
```
print('Genes in trajectory 1:', list(gene_trajectory[gene_trajectory['Pseudoorder-1'] > 0].sort_values('Pseudoorder-1', ascending=False).index))
```
which returns
```
Genes in trajectory 1: ['DEPTOR', 'PPP1R14A', 'PKIB', 'GRIP1', 'ENHO', 'CD1E', 'NDRG2', 'BCL7A', 'SLC38A1', 'BLNK', 'CD1C', 'LGMN', 'C12orf75', 'CD72', 'FCER1A', 'ATP1B1', 'CLIC2', 'HLA-DOA', 'ITM2C', 'RGS1', 'FPR3', 'TLR10', 'CD2', 'CLEC10A', 'PDLIM1', 'GFRA2', 'BIN1', 'AFF3', 'FCGR2B', 'PLD4', 'SPATS2L', 'SERPINF1', 'LMNA', 'ID3', 'VSIG4', 'EMP1', 'HLA-DQA1', 'GPR183', 'ARL4C', 'FCER2']
```

**Comment by fra-pcmgf** [comment]
Regarding the plots, it's not possible at the moment to show the gene names, but you can make a modified plotting function `plot_gene_trajectory_3d_with_labels` based on `plot_gene_trajectory_3d` which accepts an extra parameter `label_genes` with a list of gene labels to add to the plot. 

Python code
```python
import pandas as pd
import scanpy as sc
from matplotlib import pyplot as plt
from typing import Iterable, Any


def plot_gene_trajectory_3d_with_labels(
        gene_trajectory: pd.DataFrame,
        s: int = 1,
        label_genes: Iterable[str] = None,
        **kwargs: Any
) -> None:
    """
    Generate a 3D plot of a gene-trajectory object

    :param gene_trajectory: a gene trajectory result
    :param s: scatterplot point size (default: 1)
    :param label_genes: Gene labels to plot (default: None)
    :param kwargs: plot arguments that will be passed to Axes.scatter
    """
    for c in 'DM_1', 'DM_2', 'DM_3', 'selected':
        if c not in gene_trajectory.columns:
            raise ValueError(f'Column {c} is not present in gene trajectory DataFrame')

    ax = plt.axes(projection='3d')
    selections = pd.Categorical(gene_trajectory.selected)

    for c in selections.categories:
        idxs = selections == c
        ax.scatter(xs=gene_trajectory['DM_1'][idxs],
                   ys=gene_trajectory['DM_2'][idxs],
                   zs=gene_trajectory['DM_3'][idxs],
                   s=s,
                   label=c,
                   **kwargs)

    if label_genes:
        for g in label_genes:
            idx = gene_trajectory.index.get_loc(g)
            ax.text(x=gene_trajectory['DM_1'][idx],
                    y=gene_trajectory['DM_2'][idx],
                    z=gene_trajectory['DM_3'][idx],
                    s=g)
    ax.legend()
```

which you can then use to plot the first gene of each trajectory of the tutorial as 
```
plot_gene_trajectory_3d_with_labels(gene_trajectory, 
                                    label_genes=['CLEC5A', 'LYPD2', 'DEPTOR'])
```

<img width="424" alt="image" src="https://github.com/KlugerLab/GeneTrajectory-python/assets/75027217/dd28ec04-fc2f-48fc-a24e-9bea230a8823">

**Comment by yc508** [comment]
Hi, thank you very much for your help! These codes work perfectly! I have another question about the function add genes bin score. As alra doesn't have package in Python, can I use 'counts' layer in this case instead of 'alra'? Thank you very much!

**Comment by fra-pcmgf** [comment]
Sure, you can use the `counts` layer or, if you don't specify anything, it will use the data.X values

**Comment by yc508** [comment]
Thank you very much for your information!

**Comment by fra-pcmgf** [comment]
The `label_genes ` parameters was added to the in version v1.0.2
