### ISSUE TITLE
0 values after running coarse_grain_adata

### ISSUE THREAD

**Issue by to-be-so-lonely** [KlugerLab/GeneTrajectory-python#8]
Hello, thank you for developing this wonderful tool! I just have a single question:

```
run_dm(adata, reduction = "X_pca", k = 10, reduction_result = "X_dm"); print("dm completed")
cell_graph_dist = get_graph_distance(adata, k = 10, reduction = "X_dm"); print("cell graph completed")
gene_expression_updated, graph_dist_updated = coarse_grain_adata(adata, graph_dist = cell_graph_dist, features = genes, n = 1000)
```

where `len(genes) = 1000`. After running these above codes, I found out that some of the column sum values have 0 values which yields error in 88-92 lines of `gene_distance_shared.py `

```
gene_i = np.array(gene_expr_matrix[:, i]).reshape(-1)
gene_j = np.array(gene_expr_matrix[:, j]).reshape(-1)

gene_i = gene_i / sum(gene_i)
gene_j = gene_j / sum(gene_j)
```

so I removed columns with 0 sum values (actually, only one). After that, I ran

`gene_trajectory = extract_gene_trajectory(gene_embedding, gene_dist_mat, t_list = [1, 3, 1], gene_names = genes, k = 10)`

and of course it threw me error regarding unmatched indices (length of variable `genes` does not equal to input arrays of the function)

so my question is, how can I retrieve gene names (= gene names corresponding to the column indices in the picture) from any of `gene_expression_updated` or `gene_dist_mat` or `gene_embedding` so that I can extract only genes whose column sum of `gene_expression_updated` does not equal 0?

`> pd.DataFrame(gene_expression_updated)`
![image](https://github.com/KlugerLab/GeneTrajectory-python/assets/156160039/da7d5633-60a9-4219-8b80-4dee5c69c9f8)

Thank you.

**Comment by fra-pcmgf** [comment]
Hi @to-be-so-lonely, 

From what I understand you have some genes that are not expressed in any cell. 
Can you try filtering out genes with 0 expression using `select_top_genes(adata, layer='counts')` or some other tool like [sc.pp.filter_genes](https://scanpy.readthedocs.io/en/stable/generated/scanpy.pp.filter_genes.html) before running  `run_dm()`?

**Comment by to-be-so-lonely** [comment]
@fra-pcmgf 

Thank you for your message! I think that way would be more straightforward and convenient. I'll give it a try.

**Edit: Yes, sc.pp.filter_genes worked. Thank you for your help!**
